#! /usr/bin/env bash

case $1 in
install)
  git submodule update --init
  ln -s ~/.vim/vimrc ~/.vimrc
  ;;
update)
  git pull
  git submodule sync
  git submodule update --init --recursive
  ;;
*)
  echo "Use install or update" ;;
esac
